// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgYMgW_i8E5HhSUsUMQ97bmBSNHT8vLmw',
    appId: '1:656982791117:web:12b45856b969d836936a84',
    messagingSenderId: '656982791117',
    projectId: 'tictactoe-17f82',
    authDomain: 'tictactoe-17f82.firebaseapp.com',
    storageBucket: 'tictactoe-17f82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgN-KWLjs2ehXhg1Xog91MMpEkCA2dGSg',
    appId: '1:529971222496:android:9c510bf41c992e5f5dfd85',
    messagingSenderId: '529971222496',
    projectId: 'tictactoe-8d019',
    storageBucket: 'tictactoe-8d019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVckZX3dT9ptEdk9s76Svuu9lrYZU4ig',
    appId: '1:656982791117:ios:437841e63d537bae936a84',
    messagingSenderId: '656982791117',
    projectId: 'tictactoe-17f82',
    storageBucket: 'tictactoe-17f82.appspot.com',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLVckZX3dT9ptEdk9s76Svuu9lrYZU4ig',
    appId: '1:656982791117:ios:757e7732d8c8ed2b936a84',
    messagingSenderId: '656982791117',
    projectId: 'tictactoe-17f82',
    storageBucket: 'tictactoe-17f82.appspot.com',
    iosBundleId: 'com.example.tictactoe.RunnerTests',
  );
}